Repository herbakmarcell/afp2_saturn, pull requests merged in 2024-03, with the labels that each got.

#90 Dokumentáció - Képek javítása
  Docs/Funkcionális Specifikáció.md
  Docs/Rendszerterv.md
Labels: Hiba

#91 Adatbázismodell Létrehozása
  .gitignore
  Examples/appsettings.json
  Project/ASP_Core/ASP_Core.csproj
  Project/ASP_Core/Controllers/WeatherForecastController.cs
  Project/ASP_Core/Database/Models/ClassModel.cs
  Project/ASP_Core/Database/Models/Course.cs
  Project/ASP_Core/Database/Models/Exam.cs
  Project/ASP_Core/Database/Models/Grade.cs
  Project/ASP_Core/Database/Models/Role.cs
  Project/ASP_Core/Database/Models/Room.cs
  Project/ASP_Core/Database/Models/Semester.cs
  Project/ASP_Core/Database/Models/Subject.cs
  Project/ASP_Core/Database/Models/User.cs
  Project/ASP_Core/Database/SaturnContext.cs
  Project/ASP_Core/Program.cs
  Project/ASP_Core/WeatherForecast.cs
  Project/ASP_Core/appsettings.json
Labels: Backend

#95 Bejelentkezés design & felület/felhasználói adatok alapja
  Project/Project.sln
  Project/Saturn_Client/Form1.Designer.cs
  Project/Saturn_Client/Form1.cs
  Project/Saturn_Client/LoginForm.Designer.cs
  Project/Saturn_Client/LoginForm.cs
  Project/Saturn_Client/LoginForm.resx
  Project/Saturn_Client/MainForm.Designer.cs
  Project/Saturn_Client/MainForm.cs
  Project/Saturn_Client/MainForm.resx
  Project/Saturn_Client/Program.cs
  Project/Saturn_Client/Properties/Resources.Designer.cs
  Project/Saturn_Client/Properties/Resources.resx
  Project/Saturn_Client/Resources/cross.png
  Project/Saturn_Client/Resources/exit.png
  Project/Saturn_Client/Resources/exiticon.png
  Project/Saturn_Client/Resources/loginButtonpic.png
  Project/Saturn_Client/Resources/padlock.png
  Project/Saturn_Client/Resources/passkey.png
  Project/Saturn_Client/Resources/saturnbeta.png
  Project/Saturn_Client/Resources/saturnicon.ico
  Project/Saturn_Client/Resources/saturntmalpha.png
  Project/Saturn_Client/Resources/space.png
  Project/Saturn_Client/Resources/user.png
  Project/Saturn_Client/Saturn_Client.csproj
  Project/Saturn_Client/UserDataForm.Designer.cs
  Project/Saturn_Client/UserDataForm.cs
  Project/Saturn_Client/UserDataForm.resx
Labels: Frontend
